# Generated by Django 4.2b1 on 2023-03-14 13:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=100, verbose_name="Contact Number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Mail Address"
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest",
                "verbose_name_plural": "Guests",
                "ordering": ("firstname", "lastname"),
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Venue Name"),
                ),
                ("address", models.CharField(max_length=200)),
                (
                    "zip_code",
                    models.CharField(max_length=50, verbose_name="Zip Code"),
                ),
                (
                    "website",
                    models.URLField(
                        unique=True, verbose_name="Website Address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, verbose_name="Contact Number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Contact EmailID"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="venue",
                        verbose_name="Venue Picture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Event Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event Date")),
                (
                    "event_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(blank=True, to="learn.participant"),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn.venue",
                    ),
                ),
            ],
        ),
    ]
