# Generated by Django 4.2b1 on 2023-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0002_venue_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="owner",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
